SELECT
MAX(CASE string_field_0 WHEN 'Data' THEN string_field_1 ELSE NULL END) AS Data,
MAX(CASE string_field_0 WHEN 'Jedzenie' THEN string_field_1 ELSE NULL END) AS Jedzenie,
MAX(CASE string_field_0 WHEN 'Alkohol' THEN string_field_1 ELSE NULL END) AS Alkohol,
MAX(CASE string_field_0 WHEN 'Transport' THEN string_field_1 ELSE NULL END) AS Transport,
MAX(CASE string_field_0 WHEN 'Czynsz' THEN string_field_1 ELSE NULL END) AS Czynsz,
MAX(CASE string_field_0 WHEN 'Kredyt' THEN string_field_1 ELSE NULL END) AS Kredyt,
MAX(CASE string_field_0 WHEN 'Wyjścia' THEN string_field_1 ELSE NULL END) AS Wyjscia,
MAX(CASE string_field_0 WHEN 'Wyjazdy' THEN string_field_1 ELSE NULL END) AS Wyjazdy,
MAX(CASE string_field_0 WHEN 'Nauka' THEN string_field_1 ELSE NULL END) AS Nauka,
MAX(CASE string_field_0 WHEN 'Prezenty' THEN string_field_1 ELSE NULL END) AS Prezenty,
MAX(CASE string_field_0 WHEN 'Chemia i art. domowe' THEN string_field_1 ELSE NULL END) AS Chemia_i_art_domowe,
MAX(CASE string_field_0 WHEN 'Kosmetyki' THEN string_field_1 ELSE NULL END) AS Kosmetyki,
MAX(CASE string_field_0 WHEN 'Książki' THEN string_field_1 ELSE NULL END) AS Ksiazki,
MAX(CASE string_field_0 WHEN 'Ubrania i obuwie' THEN string_field_1 ELSE NULL END) AS Ubrania_i_obuwie,
MAX(CASE string_field_0 WHEN 'Zdrowie' THEN string_field_1 ELSE NULL END) AS Zdrowie,
MAX(CASE string_field_0 WHEN 'Wesele' THEN string_field_1 ELSE NULL END) AS Wesele,
MAX(CASE string_field_0 WHEN 'Wystrój mieszkania' THEN string_field_1 ELSE NULL END) AS Wystroj_mieszkania,
MAX(CASE string_field_0 WHEN 'Pozostałe' THEN string_field_1 ELSE NULL END) AS Pozostale,
MAX(CASE string_field_0 WHEN 'Rozliczenia' THEN string_field_1 ELSE NULL END) AS Rozliczenia,
MAX(CASE string_field_0 WHEN 'Wydatki' THEN string_field_1 ELSE NULL END) AS Wydatki,
MAX(CASE string_field_0 WHEN 'Przychody' THEN string_field_1 ELSE NULL END) AS Przychody,
MAX(CASE string_field_0 WHEN 'Przychody' THEN string_field_1 ELSE NULL END) AS Bilans
FROM `assets-382517.google_spreadsheet.wydatki_przychody`
